orderApp.factory('ajaxService',function(baseUrl,scopeData){
	return{
		deleteFav:function(Product,suc,err){
			return 	$.ajax({
			    type: "delete",
			    url: baseUrl + "types/"+scopeData.discountType+"/wap/"+scopeData.isMobile+'/Favorite',
			    data: {
			    	userID:scopeData.userID,
					productCode:Product.productCode
			    },
			    success:suc,
			    error:err
	  		});
		}
	}
});


orderApp.factory('AuthApiService',function($resource,baseAuthUrl,scopeData){
	return $resource(
		baseAuthUrl+":Type",
		{},
		{
			getDomainAccount:{
				method:'GET',
			}
		}
	)
})

orderApp.factory('ApiService',function($resource,baseUrl,scopeData){

	return $resource(
		baseUrl+":Type",
		{},
		{
			getCategories:{
				method:'GET',
				isArray:true
			},
			getProductList:{
				method:'GET',
				params:{
					code:'@code',
					productClass:'@productClass',
					pageNum:'@pageNum',
					userID:'@userID'
				},
				isArray:false
			},
			getSecretary:{
				method:'GET',
				params:{
					userID:'@userID'
				},
				isArray:true
			},
			getFavoriteList:{
				method:'GET',
				params:{
					userID:'@userID',
					pageNum:'@pageNum'
				}
			},
			getBalance:{
				method:'GET',
				params:{
					myBalanceUserID:'@myBalanceUserID'
				}
			},
			getOrderCount:{
				method:'GET',
				params:{
					userID:'@userID'
				}
			},
			getOrderDate:{
				method:'GET',
				isArray:false
			},
			postOrderedProduct:{
				method:'POST',
				data:{
					userID:'@userID',
					productCode:'@productCode',
					count:'@count'
				}
			},
			postFav:{
		      	method:'POST',
		      	data:{
		          userID:'@userID',
		          productCode:'@productCode'
		        }
		    },
		    getOrderList:{
		      	method:'GET',
		      	params:{
		          userID:'@userID',
		          orderDate:'@orderDate',
		          pageNum:'@pageNum'
		        }
		    },
		    getOrderData:{
		      	method:'GET',
		      	params:{
		          orderID:'@orderID',
		        },
		        isArray:true
		    },
		    getSearchTips:{
		    	method:'GET',
		    	params:{
		          key:'@key'
		        },
		        isArray:true
		    },
		    getSearchResult:{
		    	method:'GET',
		    	params:{
		          key:'@key',
		          pageNum:'@pageNum',
		          userID:'@userID'
		        },
		        isArray:false
		    },
		    postUserProfile:{
		    	method:'POST',
		    	params:{
		    		ad:'@ad',
		    	}
		    },
		    postRegist:{
		    	method:'PUT',
		    	params:{
		    		ad:'@ad',
		    	}
		    },
		    getChartData:{
		    	method:'GET',
		    		params:{
						userID:'@userID'
					}
		    },
		    postDonation:{
		    	method:'POST',
		    	data:{
		    		userID:'@userID',
		    		amount:'@amount',
		    	}
		    },
		}
	);
});

orderApp.factory('currentOrderServ',function($resource,baseUrl,scopeData){
	return $resource(
    baseUrl+'/:kind',
    {},
    {
      //获取当月订单
      getCurrentOrder:{
        method:'GET',
        params:{
          userID:'@userID',
          orderDate:'',
        },
        isArray:true
      },
      //修改当月订单产品数量
      putProduct:{
        method:'PUT',
        params:{
          kind:'@kind',
          userID:'@userID',
          productCode:'@productCode',
          count:'@count'
        }
      },
      //获取下单日期范围
      getDateGate:{
        method:'GET'
      },
      getResAmount:{
        method:'GET',
        params:{
        	myBalanceUserID:'@myBalanceUserID'
        }
      },
      postFav:{
      	method:'POST',
      	params:{
      	  kind:'@kind',
          userID:'@userID',
          productCode:'@productCode'
        }
      },
      getCount:{
      	method:'GET',
      	params:{
          userID:'@userID'
        }
      }
    }
  );
})

orderApp.factory('deleteServ',function(baseUrl,scopeData){
	function del(kind,data,suc,err){
		return 	$.ajax({
		    type: "delete",
		    url: baseUrl+"types/"+scopeData.discountType+"/wap/"+scopeData.isMobile+"/"+kind,
		    data: data,
		    success:suc,
		    error:err
  		});
	}
	return function(kind,data,suc,err){
		del(kind,data,suc,err)
	}
})
