orderApp.factory('ajaxService',function(baseUrl,scopeData){
	return{
		deleteFav:function(Product,suc,err){
			return 	$.ajax({
			    type: "delete",
			    url: baseUrl + "types/"+scopeData.discountType+"/wap/"+scopeData.isMobile+'/Favorite',
			    data: {
			    	userID:scopeData.userID,
					productCode:Product.productCode
			    },
			    success:suc,
			    error:err
	  		});
		}
	}
});

orderApp.factory('ApiService',function($resource,baseUrl,scopeData){
	
	return $resource(
		baseUrl+":Type",
		{},
		{
			getCategories:{
				method:'GET',
				isArray:true
			},
			getProductList:{
				method:'GET',
				params:{
					code:'@code',
					productClass:'@productClass',
					pageNum:'@pageNum',
					userID:'@userID'
				},
				isArray:false
			},
			getSecretary:{
				method:'GET',
				params:{
					userID:'@userID'
				},
				isArray:true
			},
			getFavoriteList:{
				method:'GET',
				params:{
					userID:'@userID',
					pageNum:'@pageNum'
				}
			},
			getBalance:{
				method:'GET',
				params:{
					myBalanceUserID:'@myBalanceUserID'
				}
			},
			getOrderCount:{
				method:'GET',
				params:{
					userID:'@userID'
				}
			},
			getOrderDate:{
				method:'GET',
				isArray:false
			},
			postOrderedProduct:{
				method:'POST',
				data:{
					userID:'@userID',
					productCode:'@productCode',
					count:'@count'
				}
			},
			postFav:{
		      	method:'POST',
		      	data:{
		          userID:'@userID',
		          productCode:'@productCode'
		        }
		    },
		    getOrderList:{
		      	method:'GET',
		      	params:{
		          userID:'@userID',
		          orderDate:'@orderDate',
		          pageNum:'@pageNum'
		        }
		    },
		    getOrderData:{
		      	method:'GET',
		      	params:{
		          orderID:'@orderID',
		        },
		        isArray:true
		    },
		    getSearchTips:{
		    	method:'GET',
		    	params:{
		          key:'@key'
		        },
		        isArray:true
		    },
		    getSearchResult:{
		    	method:'GET',
		    	params:{
		          key:'@key',
		          pageNum:'@pageNum',
		          userID:'@userID'
		        },
		        isArray:false
		    },
		    postUserProfile:{
		    	method:'POST',
		    	params:{
		    	}
		    },
		    postRegist:{
		    	method:'PUT',
		    	params:{
		    	}
		    },
		    getChartData:{
		    	method:'GET',
		    	params:{
					userID:'@userID'
				}
		    }
		}
	);
});